spring:
  #redis数据库连接
  redis:
    host: ${REDIS_URL:localhost}
    port: ${REDIS_PORT:6379}
    #username: ${REDIS_USERNAME:default}
    password: ${REDIS_PASSWROD:635123}
    database: ${REDIS_DATABASE:0}
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    connect-timeout: 6400
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/sharemount?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWROD:635123}
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: ${SERVLET_MAX_FILE_SIZE:100MB}
      max-request-size: ${SERVLET_MAX_REQUEST_SIZE:100MB}
  #自动执行sql脚本
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  config:
    additional-location: file:${PATH_TO_CONFIG:"./"}/config.yml
  mail:
    # 发送者邮箱
    username: 1466450232@qq.com
    #申请到的授权码
    password: rkzpmwtiefqhgdja
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 端口号465或587
    port: 465
    protocol: smtps
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


pathToConfig: ${PATH_TO_CONFIG:.}
